name: CI
on:
  push:
    branches: 
            - main
  pull_request:
    branches:
            - main
  schedule:
  - cron: "0 2 * * 1-5"
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Dependencies Newman
        run: npm install newman
      
      - name: Install Dependencies Newman HTML Extra Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run PlaySmart collection
        run: newman run -x "postman/collections/restful-booker_880f2503-8ffd-4e76-9161-58262bc0c334.json" -e "postman/schemas/PlaySmart Environment 1.0.0.postman_environment.json" --reporters junit --reporter-junit-export Results\junitReport.xml --bail
